name: aws-xray-client-wai
version: 0.1.0.1
github:  "freckle/aws-xray-client"
license: MIT
author: "Freckle R&D"
maintainer: "engineering@freckle.com"
copyright: "2021 Renaissance Learning Inc"
synopsis: A client for AWS X-Ray integration with WAI.
description: |
  Works with `aws-xray-client` to enable X-Ray tracing with WAI.

extra-source-files:
  - README.md
  - CHANGELOG.md

dependencies:
  - base < 5

default-extensions:
  - BangPatterns
  - DataKinds
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies

library:
  source-dirs: library
  dependencies:
    - aws-xray-client
    - bytestring
    - containers
    - http-types
    - lens
    - random
    - text
    - time
    - unliftio
    - unliftio-core
    - vault
    - wai
